### ISSUE TITLE
What is the right way to include all files in a project?

### ISSUE THREAD

**Issue by dmitry-js** [mrvlasyuk/tiny_code_improver#2]
If we want to include all files in a directory, we usually use a wildcard `*` or `**` in case of all files in all subdirectories. But it doesn't work in this library. Example:

```
project_name: "My project"
directory: "./src/app"
files: ["*"]
```

There could be a lot of files in the project and it's not flexible to include each one
```
files:
  - file1.py
  - file2.py
  - file3.py
  - ...
```

**Comment by mrvlasyuk** [comment]
Nice idea! I will implement that 👍

**Comment by mrvlasyuk** [comment]
Done in 6c68fe0.
